In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/credit_card_approval_dataset.csv")
df.head()

,Candidate Name,Age,Gender,Salary,Income,Job Details,Credit History,Credit Score,Existing Loans,Credit Status
0,Anjali Jain,22,Female,72978,80494,Consultant,Bad,521,2,Rejected
1,Rahul Iyer,23,Female,85895,88953,Accountant,Bad,379,0,Rejected
2,Amit Kumar,46,Female,58514,61636,Teacher,No History,473,2,Rejected
3,Arjun Devi,57,Male,94444,102156,Software Engineer,Good,375,2,Rejected
4,Rahul Babu,58,Male,20894,27545,Teacher,Good,676,3,Rejected

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Candidate Name  1000 non-null   object
 1   Age             1000 non-null   int64
 2   Gender          1000 non-null   object
 3   Salary          1000 non-null   int64
 4   Income          1000 non-null   int64
 5   Job Details     1000 non-null   object
 6   Credit History  1000 non-null   object
 7   Credit Score    1000 non-null   int64
 8   Existing Loans  1000 non-null   int64
 9   Credit Status   1000 non-null   object
dtypes: int64(5), object(5)
memory usage: 78.3+ KB

In [5]:
df.isnull().sum()

Candidate Name    0
Age               0
Gender            0
Salary            0
Income            0
Job Details       0
Credit History    0
Credit Score      0
Existing Loans    0
Credit Status     0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)

In [8]:
df.fillna("Unknown",inplace=True)

In [9]:
df.columns=df.columns.str.strip()

In [10]:
df.to_csv("cleaned_dataset.csv",index=False)